---
defaults:
  - wakehurst
  - _self_

train_transforms:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: landscapes.transforms.ConvertPILImage
      mode: RGB
    - _target_: torchvision.transforms.Resize
      size: 224
      interpolation:
        _target_: torchvision.transforms.functional.InterpolationMode
        value: bicubic
    - _target_: torchvision.transforms.CenterCrop
      size: 224
    - _target_: torchvision.transforms.TrivialAugmentWide
    - _target_: torchvision.transforms.ToTensor
    # - _target_: torchvision.transforms.RandomErasing
      # p: 0.1
      # value: 0
    - _target_: torchvision.transforms.Normalize 
      mean: [0.48145466, 0.4578275, 0.40821073]
      std: [0.26862954, 0.26130258, 0.27577711]

test_transforms:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: landscapes.transforms.ConvertPILImage
      mode: RGB
    - _target_: torchvision.transforms.Resize
      size: 224
      interpolation:
        _target_: torchvision.transforms.functional.InterpolationMode
        value: bicubic
    - _target_: torchvision.transforms.CenterCrop
      size: 224
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize 
      mean: [0.48145466, 0.4578275, 0.40821073]
      std: [0.26862954, 0.26130258, 0.27577711]
