---
defaults:
  - /schema/alg: erm
  - defaults
  - _self_
model: 
metrics: 
lr: 0.0005
label_smoothing: 0.1
optimizer_cls: 'torch.optim.AdamW'
optimizer_kwargs: null
use_sam: false
sam_rho: 0.05
scheduler_cls: null
scheduler_kwargs: null
lr_sched_interval: epoch
lr_sched_freq: 1
batch_transforms:
  - _target_: landscapes.transforms.RandomCutmix
    alpha: 1.0
    num_classes: 5
