---
defaults:
  - /schema/alg: erm
  - defaults
  - _self_
model: 
metrics: 
lr: 0.0005
label_smoothing: 0.1
optimizer_cls: 'torch.optim.AdamW'
optimizer_kwargs: 
  weight_decay: 0
use_sam: false
sam_rho: 0.05
scheduler_cls: landscapes.schedulers.LinearWarmupCosineAnnealingLR
scheduler_kwargs: 
  warmup_epochs: 10000
  max_epochs: 80000
  warmup_start_lr: 1.0e-3
  eta_min: 5.0e-7
  last_epoch: -1
lr_sched_interval: step
lr_sched_freq: 1
batch_transforms:
  - _target_: landscapes.transforms.RandomCutMix
    alpha: 1.0
    num_classes: 5
  - _target_: ranzen.torch.transforms.RandomMixUp.with_beta_dist
    alpha: 0.2
    num_classes: 5
    inplace: true
